### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pduff-code**
Updated Monopile+Scour and Transition Piece cost equations.

### CODE REVIEW

**Comment by grantbuster** [comment]
hey @pduff-code can you put this in a subfolder in the analysis library? we're adding all sorts of new models to NRWAL and want to keep them organized.

**Comment by pduff-code** [comment]
Sounds good

**Comment by pduff-code** [comment]
It should be okay now.

**Comment by grantbuster** [comment]
hey @pduff-code can you fix the yaml equation syntax? You put this:
```
eqn:
    eqn = stuff
```
but it should be this:
```
eqn:
    stuff

**Review by grantbuster — APPROVED** [review]

**Pull request merged**
